/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ENACHDetails = IDL.Record({
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'accountHolder' : IDL.Text,
});
export const EmploymentType = IDL.Variant({
  'salaried' : IDL.Null,
  'selfEmployed' : IDL.Null,
});
export const LoanTenure = IDL.Variant({
  'twelveMonths' : IDL.Null,
  'threeMonths' : IDL.Null,
  'sixMonths' : IDL.Null,
});
export const NewApplication = IDL.Record({
  'cibilScore' : IDL.Nat,
  'enachDetails' : ENACHDetails,
  'employmentType' : EmploymentType,
  'tenure' : LoanTenure,
  'amount' : IDL.Nat,
  'employmentDetails' : IDL.Text,
  'monthlyIncome' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LoanStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const LoanApplicationPublic = IDL.Record({
  'status' : LoanStatus,
  'applicant' : IDL.Principal,
  'cibilScore' : IDL.Nat,
  'enachDetails' : ENACHDetails,
  'employmentType' : EmploymentType,
  'tenure' : LoanTenure,
  'amount' : IDL.Nat,
  'employmentDetails' : IDL.Text,
  'applicationTime' : Time,
  'monthlyIncome' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForLoan' : IDL.Func([NewApplication], [IDL.Nat], []),
  'approveApplication' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateEMI' : IDL.Func(
      [IDL.Nat, LoanTenure],
      [
        IDL.Record({
          'principal' : IDL.Nat,
          'interest' : IDL.Nat,
          'tenureMonths' : IDL.Nat,
          'totalPayable' : IDL.Nat,
          'monthlyEMI' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'checkEligibility' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
  'deleteApplication' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplicationPublic)],
      ['query'],
    ),
  'getApplication' : IDL.Func([IDL.Nat], [LoanApplicationPublic], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplicationPublic)],
      ['query'],
    ),
  'getPendingApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplicationPublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'modifyApplication' : IDL.Func([IDL.Nat, NewApplication], [], []),
  'rejectApplication' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ENACHDetails = IDL.Record({
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  const EmploymentType = IDL.Variant({
    'salaried' : IDL.Null,
    'selfEmployed' : IDL.Null,
  });
  const LoanTenure = IDL.Variant({
    'twelveMonths' : IDL.Null,
    'threeMonths' : IDL.Null,
    'sixMonths' : IDL.Null,
  });
  const NewApplication = IDL.Record({
    'cibilScore' : IDL.Nat,
    'enachDetails' : ENACHDetails,
    'employmentType' : EmploymentType,
    'tenure' : LoanTenure,
    'amount' : IDL.Nat,
    'employmentDetails' : IDL.Text,
    'monthlyIncome' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LoanStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const LoanApplicationPublic = IDL.Record({
    'status' : LoanStatus,
    'applicant' : IDL.Principal,
    'cibilScore' : IDL.Nat,
    'enachDetails' : ENACHDetails,
    'employmentType' : EmploymentType,
    'tenure' : LoanTenure,
    'amount' : IDL.Nat,
    'employmentDetails' : IDL.Text,
    'applicationTime' : Time,
    'monthlyIncome' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForLoan' : IDL.Func([NewApplication], [IDL.Nat], []),
    'approveApplication' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateEMI' : IDL.Func(
        [IDL.Nat, LoanTenure],
        [
          IDL.Record({
            'principal' : IDL.Nat,
            'interest' : IDL.Nat,
            'tenureMonths' : IDL.Nat,
            'totalPayable' : IDL.Nat,
            'monthlyEMI' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'checkEligibility' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
    'deleteApplication' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplicationPublic)],
        ['query'],
      ),
    'getApplication' : IDL.Func([IDL.Nat], [LoanApplicationPublic], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplicationPublic)],
        ['query'],
      ),
    'getPendingApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplicationPublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'modifyApplication' : IDL.Func([IDL.Nat, NewApplication], [], []),
    'rejectApplication' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };