/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ENACHDetails {
  'ifscCode' : string,
  'bankName' : string,
  'accountNumber' : string,
  'accountHolder' : string,
}
export type EmploymentType = { 'salaried' : null } |
  { 'selfEmployed' : null };
export interface LoanApplicationPublic {
  'status' : LoanStatus,
  'applicant' : Principal,
  'cibilScore' : bigint,
  'enachDetails' : ENACHDetails,
  'employmentType' : EmploymentType,
  'tenure' : LoanTenure,
  'amount' : bigint,
  'employmentDetails' : string,
  'applicationTime' : Time,
  'monthlyIncome' : bigint,
}
export type LoanStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type LoanTenure = { 'twelveMonths' : null } |
  { 'threeMonths' : null } |
  { 'sixMonths' : null };
export interface NewApplication {
  'cibilScore' : bigint,
  'enachDetails' : ENACHDetails,
  'employmentType' : EmploymentType,
  'tenure' : LoanTenure,
  'amount' : bigint,
  'employmentDetails' : string,
  'monthlyIncome' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForLoan' : ActorMethod<[NewApplication], bigint>,
  'approveApplication' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateEMI' : ActorMethod<
    [bigint, LoanTenure],
    {
      'principal' : bigint,
      'interest' : bigint,
      'tenureMonths' : bigint,
      'totalPayable' : bigint,
      'monthlyEMI' : bigint,
    }
  >,
  'checkEligibility' : ActorMethod<[bigint, bigint], boolean>,
  'deleteApplication' : ActorMethod<[bigint], undefined>,
  'getAllApplications' : ActorMethod<[], Array<LoanApplicationPublic>>,
  'getApplication' : ActorMethod<[bigint], LoanApplicationPublic>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyApplications' : ActorMethod<[], Array<LoanApplicationPublic>>,
  'getPendingApplications' : ActorMethod<[], Array<LoanApplicationPublic>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modifyApplication' : ActorMethod<[bigint, NewApplication], undefined>,
  'rejectApplication' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];