/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewApplication {
    cibilScore: bigint;
    enachDetails: ENACHDetails;
    employmentType: EmploymentType;
    tenure: LoanTenure;
    amount: bigint;
    employmentDetails: string;
    monthlyIncome: bigint;
}
export type Time = bigint;
export interface LoanApplicationPublic {
    status: LoanStatus;
    applicant: Principal;
    cibilScore: bigint;
    enachDetails: ENACHDetails;
    employmentType: EmploymentType;
    tenure: LoanTenure;
    amount: bigint;
    employmentDetails: string;
    applicationTime: Time;
    monthlyIncome: bigint;
}
export interface ENACHDetails {
    ifscCode: string;
    bankName: string;
    accountNumber: string;
    accountHolder: string;
}
export enum EmploymentType {
    salaried = "salaried",
    selfEmployed = "selfEmployed"
}
export enum LoanStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum LoanTenure {
    twelveMonths = "twelveMonths",
    threeMonths = "threeMonths",
    sixMonths = "sixMonths"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyForLoan(newApp: NewApplication): Promise<bigint>;
    approveApplication(applicationId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateEMI(amount: bigint, tenure: LoanTenure): Promise<{
        principal: bigint;
        interest: bigint;
        tenureMonths: bigint;
        totalPayable: bigint;
        monthlyEMI: bigint;
    }>;
    checkEligibility(cibilScore: bigint, amount: bigint): Promise<boolean>;
    deleteApplication(applicationId: bigint): Promise<void>;
    getAllApplications(): Promise<Array<LoanApplicationPublic>>;
    getApplication(applicationId: bigint): Promise<LoanApplicationPublic>;
    getCallerUserRole(): Promise<UserRole>;
    getMyApplications(): Promise<Array<LoanApplicationPublic>>;
    getPendingApplications(): Promise<Array<LoanApplicationPublic>>;
    isCallerAdmin(): Promise<boolean>;
    modifyApplication(applicationId: bigint, updatedApp: NewApplication): Promise<void>;
    rejectApplication(applicationId: bigint): Promise<void>;
}
import type { ENACHDetails as _ENACHDetails, EmploymentType as _EmploymentType, LoanApplicationPublic as _LoanApplicationPublic, LoanStatus as _LoanStatus, LoanTenure as _LoanTenure, NewApplication as _NewApplication, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyForLoan(arg0: NewApplication): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForLoan(to_candid_NewApplication_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForLoan(to_candid_NewApplication_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveApplication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateEMI(arg0: bigint, arg1: LoanTenure): Promise<{
        principal: bigint;
        interest: bigint;
        tenureMonths: bigint;
        totalPayable: bigint;
        monthlyEMI: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateEMI(arg0, to_candid_LoanTenure_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateEMI(arg0, to_candid_LoanTenure_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkEligibility(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEligibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEligibility(arg0, arg1);
            return result;
        }
    }
    async deleteApplication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApplication(arg0);
            return result;
        }
    }
    async getAllApplications(): Promise<Array<LoanApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: bigint): Promise<LoanApplicationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_LoanApplicationPublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_LoanApplicationPublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<LoanApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingApplications(): Promise<Array<LoanApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingApplications();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingApplications();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async modifyApplication(arg0: bigint, arg1: NewApplication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifyApplication(arg0, to_candid_NewApplication_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifyApplication(arg0, to_candid_NewApplication_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async rejectApplication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplication(arg0);
            return result;
        }
    }
}
function from_candid_EmploymentType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplicationPublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplicationPublic): LoanApplicationPublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LoanStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LoanTenure_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanTenure): LoanTenure {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LoanStatus;
    applicant: Principal;
    cibilScore: bigint;
    enachDetails: _ENACHDetails;
    employmentType: _EmploymentType;
    tenure: _LoanTenure;
    amount: bigint;
    employmentDetails: string;
    applicationTime: _Time;
    monthlyIncome: bigint;
}): {
    status: LoanStatus;
    applicant: Principal;
    cibilScore: bigint;
    enachDetails: ENACHDetails;
    employmentType: EmploymentType;
    tenure: LoanTenure;
    amount: bigint;
    employmentDetails: string;
    applicationTime: Time;
    monthlyIncome: bigint;
} {
    return {
        status: from_candid_LoanStatus_n12(_uploadFile, _downloadFile, value.status),
        applicant: value.applicant,
        cibilScore: value.cibilScore,
        enachDetails: value.enachDetails,
        employmentType: from_candid_EmploymentType_n14(_uploadFile, _downloadFile, value.employmentType),
        tenure: from_candid_LoanTenure_n16(_uploadFile, _downloadFile, value.tenure),
        amount: value.amount,
        employmentDetails: value.employmentDetails,
        applicationTime: value.applicationTime,
        monthlyIncome: value.monthlyIncome
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LoanStatus {
    return "pending" in value ? LoanStatus.pending : "approved" in value ? LoanStatus.approved : "rejected" in value ? LoanStatus.rejected : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salaried: null;
} | {
    selfEmployed: null;
}): EmploymentType {
    return "salaried" in value ? EmploymentType.salaried : "selfEmployed" in value ? EmploymentType.selfEmployed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twelveMonths: null;
} | {
    threeMonths: null;
} | {
    sixMonths: null;
}): LoanTenure {
    return "twelveMonths" in value ? LoanTenure.twelveMonths : "threeMonths" in value ? LoanTenure.threeMonths : "sixMonths" in value ? LoanTenure.sixMonths : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplicationPublic>): Array<LoanApplicationPublic> {
    return value.map((x)=>from_candid_LoanApplicationPublic_n10(_uploadFile, _downloadFile, x));
}
function to_candid_EmploymentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LoanTenure_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanTenure): _LoanTenure {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_NewApplication_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewApplication): _NewApplication {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cibilScore: bigint;
    enachDetails: ENACHDetails;
    employmentType: EmploymentType;
    tenure: LoanTenure;
    amount: bigint;
    employmentDetails: string;
    monthlyIncome: bigint;
}): {
    cibilScore: bigint;
    enachDetails: _ENACHDetails;
    employmentType: _EmploymentType;
    tenure: _LoanTenure;
    amount: bigint;
    employmentDetails: string;
    monthlyIncome: bigint;
} {
    return {
        cibilScore: value.cibilScore,
        enachDetails: value.enachDetails,
        employmentType: to_candid_EmploymentType_n3(_uploadFile, _downloadFile, value.employmentType),
        tenure: to_candid_LoanTenure_n5(_uploadFile, _downloadFile, value.tenure),
        amount: value.amount,
        employmentDetails: value.employmentDetails,
        monthlyIncome: value.monthlyIncome
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    salaried: null;
} | {
    selfEmployed: null;
} {
    return value == EmploymentType.salaried ? {
        salaried: null
    } : value == EmploymentType.selfEmployed ? {
        selfEmployed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanTenure): {
    twelveMonths: null;
} | {
    threeMonths: null;
} | {
    sixMonths: null;
} {
    return value == LoanTenure.twelveMonths ? {
        twelveMonths: null
    } : value == LoanTenure.threeMonths ? {
        threeMonths: null
    } : value == LoanTenure.sixMonths ? {
        sixMonths: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
